[project]
name = "sentinel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=4.4.1",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.1",
    "uvloop>=0.22.1",
    "watchfiles>=1.2.0",
]

[project.scripts]
stl = "cli.cli.cli"