CREATE TABLE market_features (
    symbol VARCHAR(32) NOT NULL,
    interval VARCHAR(16) NOT NULL,
    open_time BIGINT NOT NULL,
    date_time TIMESTAMPTZ NOT NULL,

    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    close_time TIMESTAMPTZ,
    quote_volume DOUBLE PRECISION,
    trades_count BIGINT,
    taker_buy_volume DOUBLE PRECISION,
    taker_buy_quote_volume DOUBLE PRECISION,

    ret_1b DOUBLE PRECISION,
    ret_open_to_close DOUBLE PRECISION,
    ret_3b DOUBLE PRECISION,
    ret_5b DOUBLE PRECISION,
    ret_10b DOUBLE PRECISION,
    ret_20b DOUBLE PRECISION,
    ret_60b DOUBLE PRECISION,

    hl_range DOUBLE PRECISION,
    body_range DOUBLE PRECISION,
    dist_sma_20 DOUBLE PRECISION,
    dist_sma_50 DOUBLE PRECISION,
    dist_sma_200 DOUBLE PRECISION,
    ema_diff_9_21 DOUBLE PRECISION,
    ema_diff_21_50 DOUBLE PRECISION,
    vol_20 DOUBLE PRECISION,
    vol_60 DOUBLE PRECISION,
    atr_14_norm DOUBLE PRECISION,
    volume_sma_20 DOUBLE PRECISION,
    volume_rel_20 DOUBLE PRECISION,
    taker_buy_vol_ratio DOUBLE PRECISION,
    rsi_14 DOUBLE PRECISION,
    macd DOUBLE PRECISION,
    macd_signal DOUBLE PRECISION,
    macd_hist DOUBLE PRECISION,
    bb_upper DOUBLE PRECISION,
    bb_lower DOUBLE PRECISION,
    bb_width DOUBLE PRECISION,
    bb_pct DOUBLE PRECISION,
    obv DOUBLE PRECISION,
    returns_skew_20 DOUBLE PRECISION,
    returns_kurt_20 DOUBLE PRECISION,
    drawdown DOUBLE PRECISION,
    amihud_illiquidity DOUBLE PRECISION,
    return_mean_20 DOUBLE PRECISION,
    return_std_20 DOUBLE PRECISION,
    return_zscore_20 DOUBLE PRECISION,
    return_zscore_60 DOUBLE PRECISION,

    upper_wick DOUBLE PRECISION,
    lower_wick DOUBLE PRECISION,
    upper_wick_ratio DOUBLE PRECISION,
    lower_wick_ratio DOUBLE PRECISION,
    body_to_range DOUBLE PRECISION,

    price_zscore_20 DOUBLE PRECISION,
    price_zscore_50 DOUBLE PRECISION,
    price_zscore_200 DOUBLE PRECISION,
    high_distance_20 DOUBLE PRECISION,
    low_distance_20 DOUBLE PRECISION,

    volume_zscore_20 DOUBLE PRECISION,
    volume_zscore_60 DOUBLE PRECISION,
    volume_change_1 DOUBLE PRECISION,
    volume_change_5 DOUBLE PRECISION,
    vol_ratio_20_60 DOUBLE PRECISION,
    volume_trend_20 DOUBLE PRECISION,
    vol_change_1 DOUBLE PRECISION,
    vol_change_5 DOUBLE PRECISION,

    atr_ratio DOUBLE PRECISION,
    rsi_change_1 DOUBLE PRECISION,
    rsi_change_5 DOUBLE PRECISION,
    macd_hist_change_1 DOUBLE PRECISION,
    macd_hist_change_5 DOUBLE PRECISION,
    macd_hist_zscore_20 DOUBLE PRECISION,

    bb_width_change DOUBLE PRECISION,
    bb_width_zscore_20 DOUBLE PRECISION,
    bb_pct_change DOUBLE PRECISION,
    buy_pressure_change DOUBLE PRECISION,
    trade_count_change DOUBLE PRECISION,
    trade_count_zscore_20 DOUBLE PRECISION,

    avg_trade_size DOUBLE PRECISION,
    avg_trade_size_zscore_20 DOUBLE PRECISION,
    drawdown_change DOUBLE PRECISION,
    drawdown_duration BIGINT,
    recovery_from_drawdown DOUBLE PRECISION,

    target_return_1h DOUBLE PRECISION,
    target_return_4h DOUBLE PRECISION,
    target_return_12h DOUBLE PRECISION,
    target_return_24h DOUBLE PRECISION,
    target_return_72h DOUBLE PRECISION,

    target_direction_1h SMALLINT,
    target_direction_4h SMALLINT,
    target_direction_12h SMALLINT,
    target_direction_24h SMALLINT,
    target_direction_72h SMALLINT,

    target_volatility_4h DOUBLE PRECISION,
    target_volatility_24h DOUBLE PRECISION,
    target_volatility_72h DOUBLE PRECISION,

    target_log_return_1h DOUBLE PRECISION,
    target_log_return_4h DOUBLE PRECISION,
    target_log_return_12h DOUBLE PRECISION,
    target_log_return_24h DOUBLE PRECISION,
    target_log_return_72h DOUBLE PRECISION,

    PRIMARY KEY (symbol, interval, open_time)
);

CREATE INDEX idx_market_features_open_time
    ON market_features (open_time);

CREATE INDEX idx_market_features_symbol_time
    ON market_features (symbol, open_time);