-- this data/sql is generated by claude to check that the schema.sql works


INSERT INTO market_data (ticker, date, open, high, low, close, volume) VALUES
('AAPL',  '2024-01-02', 185.12, 186.50, 184.30, 185.85, 72345678),
('MSFT',  '2024-01-02', 374.20, 376.80, 373.10, 375.40, 23456789),
('GOOGL', '2024-01-02', 140.50, 141.80, 139.90, 141.20, 18234567),
('AMZN',  '2024-01-02', 153.40, 154.90, 152.80, 154.20, 34567890),
('TSLA',  '2024-01-02', 248.50, 251.20, 247.30, 250.10, 98765432),
('NVDA',  '2024-01-02', 495.20, 498.70, 493.10, 497.40, 45678901),
('META',  '2024-01-02', 358.90, 361.40, 357.20, 360.10, 19876543),
('JPM',   '2024-01-02', 168.30, 169.80, 167.50, 169.20, 12345678),
('V',     '2024-01-02', 252.10, 253.80, 251.40, 253.20, 8765432),
('JNJ',   '2024-01-02', 158.40, 159.60, 157.80, 158.90, 7654321)
ON CONFLICT (ticker, date) DO NOTHING;


INSERT INTO crypto_prices (symbol, date, open, high, low, close, volume, market_cap) VALUES
('BTC-USD', '2024-01-02', 42380.50, 43200.00, 42100.30, 42890.70, 28456789012.50, 839234567890.00),
('ETH-USD', '2024-01-02', 2280.40, 2310.80, 2265.10, 2298.60, 12345678901.30, 276543210987.00),
('SOL-USD', '2024-01-02', 102.30, 105.80, 101.40, 104.20, 3456789012.80, 45678901234.00),
('BNB-USD', '2024-01-02', 312.50, 315.90, 310.80, 314.30, 1234567890.40, 48234567890.00),
('XRP-USD', '2024-01-02', 0.6120, 0.6280, 0.6080, 0.6210, 2345678901.20, 33456789012.00)
ON CONFLICT (symbol, date) DO NOTHING;

INSERT INTO economic_indicators (series_id, date, value) VALUES
('DFF',      '2024-01-02', 5.33),   -- Fed Funds Rate
('CPIAUCSL', '2024-01-01', 308.42), -- CPI All Urban Consumers
('UNRATE',   '2024-01-01', 3.70),   -- Unemployment Rate
('GDP',      '2023-10-01', 27610.1),-- GDP (quarterly)
('T10Y2Y',   '2024-01-02', -0.41),  -- 10Y-2Y Treasury Spread
('VIXCLS',   '2024-01-02', 13.21),  -- VIX Volatility Index
('DTWEXBGS', '2024-01-02', 122.45), -- USD Trade Weighted Index
('MORTGAGE30US', '2024-01-04', 6.62)-- 30-Year Mortgage Rate
ON CONFLICT (series_id, date) DO NOTHING;


INSERT INTO news_sentiment (ticker, headline, source, published_at, sentiment, score) VALUES
('AAPL', 'Apple Vision Pro launch drives record pre-orders', 'Reuters', '2024-01-02 09:30:00+00', 'positive', 0.87),
('TSLA', 'Tesla misses Q4 delivery estimates amid price war concerns', 'Bloomberg', '2024-01-02 11:15:00+00', 'negative', -0.72),
('NVDA', 'Nvidia data center revenue surges on AI chip demand', 'CNBC', '2024-01-02 10:00:00+00', 'positive', 0.91),
('MSFT', 'Microsoft Azure growth slows slightly in latest quarter', 'WSJ', '2024-01-02 14:30:00+00', 'neutral', 0.12),
('BTC-USD', 'Bitcoin ETF approval expected imminently say analysts', 'CoinDesk', '2024-01-02 08:00:00+00', 'positive', 0.83);